BEGIN;

CREATE TABLE IF NOT EXISTS public.mpesa_transactions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id integer NOT NULL REFERENCES public.invoices(id) ON DELETE RESTRICT,
    phone text NOT NULL,
    amount_kes integer NOT NULL CHECK (amount_kes > 0),
    merchant_request_id text,
    checkout_request_id text NOT NULL UNIQUE,
    status text NOT NULL CHECK (status IN ('pending','success','failed','cancelled','timeout')) DEFAULT 'pending',
    result_code integer,
    result_desc text,
    mpesa_receipt_number text UNIQUE,
    transaction_date timestamptz,
    raw_callback jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS mpesa_transactions_invoice_id_idx ON public.mpesa_transactions(invoice_id);
CREATE INDEX IF NOT EXISTS mpesa_transactions_checkout_request_id_idx ON public.mpesa_transactions(checkout_request_id);

COMMIT;
