-- Single authoritative inventory schema. Clean slate: legacy inventory data is not migrated.
BEGIN;
CREATE TABLE IF NOT EXISTS catalog_categories (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL UNIQUE,slug TEXT NOT NULL UNIQUE,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS catalog_products (id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,sku TEXT NOT NULL UNIQUE,barcode TEXT NOT NULL UNIQUE,category_id BIGINT NOT NULL REFERENCES catalog_categories(id) ON DELETE RESTRICT,selling_price NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (selling_price >= 0),supplier TEXT,is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS branch_inventory (id BIGSERIAL PRIMARY KEY,product_id BIGINT NOT NULL REFERENCES catalog_products(id) ON DELETE CASCADE,branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,quantity_on_hand NUMERIC(14,3) NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),reorder_level NUMERIC(14,3) NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(product_id,branch_id));
CREATE INDEX IF NOT EXISTS idx_catalog_products_category_active ON catalog_products(category_id) WHERE is_active;
CREATE INDEX IF NOT EXISTS idx_branch_inventory_branch_product ON branch_inventory(branch_id,product_id);
CREATE TABLE IF NOT EXISTS inventory_movements (id BIGSERIAL PRIMARY KEY,product_id BIGINT NOT NULL REFERENCES catalog_products(id) ON DELETE RESTRICT,branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,movement_type TEXT NOT NULL CHECK (movement_type IN ('received','sold','returned','adjusted','transferred_in','transferred_out','voided')),quantity_change NUMERIC(14,3) NOT NULL CHECK (quantity_change <> 0),quantity_before NUMERIC(14,3) NOT NULL CHECK (quantity_before >= 0),quantity_after NUMERIC(14,3) NOT NULL CHECK (quantity_after >= 0),reference_type TEXT,reference_id TEXT,notes TEXT,created_by TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_inventory_movements_product_branch_created ON inventory_movements(product_id,branch_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_reference ON inventory_movements(reference_type,reference_id);
COMMIT;
