import React, { createContext, useContext, useState, ReactNode } from 'react';
import { setAuthTokenGetter, setBaseUrl } from '@workspace/api-client-react';

// API operation paths generated by the client already start with /api.
// Keep the origin-relative base empty unless an explicit non-/api external
// endpoint is configured, preventing /api + /api/... => /api/api/....
const configuredBaseUrl = import.meta.env.VITE_API_BASE_URL ?? '';
setBaseUrl(configuredBaseUrl === '/api' ? '' : configuredBaseUrl);

interface User {
  id: number;
  name: string;
  email: string;
  role: string;
  branch?: string | null;
  phone?: string | null;
}

interface AuthContextType {
  user: User | null;
  token: string | null;
  login: (token: string, user: User) => void;
  logout: () => void;
}

const AuthContext = createContext<AuthContextType | null>(null);

export function AuthProvider({ children }: { children: ReactNode }) {
  const [user, setUser] = useState<User | null>(() => {
    try {
      const stored = localStorage.getItem('user');
      return stored ? JSON.parse(stored) : null;
    } catch {
      return null;
    }
  });

  const [token, setToken] = useState<string | null>(() => localStorage.getItem('token'));

  // Install the token getter synchronously before descendants can start
  // React Query requests. The previous useEffect ran after the initial render,
  // allowing authenticated requests to leave without an Authorization header.
  setAuthTokenGetter(token ? () => token : null);

  const login = (newToken: string, newUser: User) => {
    localStorage.setItem('token', newToken);
    localStorage.setItem('user', JSON.stringify(newUser));
    setToken(newToken);
    setUser(newUser);
    setAuthTokenGetter(() => newToken);
  };

  const logout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('user');
    setToken(null);
    setUser(null);
    setAuthTokenGetter(null);
  };

  return (
    <AuthContext.Provider value={{ user, token, login, logout }}>
      {children}
    </AuthContext.Provider>
  );
}

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (!context) throw new Error("useAuth must be used within an AuthProvider");
  return context;
};
