'use strict';

const { Pool } = require('pg');
const { parseAndValidateDatabaseUrl, railwaySsl } = require('../scripts/database-url.cjs');
const TYPES = new Set(['OPENING_BALANCE','PURCHASE_RECEIPT','SALE','SALE_REVERSAL','ADJUSTMENT_IN','ADJUSTMENT_OUT','TRANSFER_OUT','TRANSFER_IN','CUSTOMER_RETURN','SUPPLIER_RETURN']);
let pool;
function db(){if(!pool){const {databaseUrl}=parseAndValidateDatabaseUrl('inventory-v3');pool=new Pool({connectionString:databaseUrl,ssl:railwaySsl(databaseUrl),max:10});}return pool;}
function n(v,label,negative=false){const x=Number(v);if(!Number.isFinite(x)||(!negative&&x<0))throw new Error(`Invalid ${label}`);return x;}
function s(v){return String(v??'').trim();}
async function tx(work){const c=await db().connect();try{await c.query('BEGIN');const r=await work(c);await c.query('COMMIT');return r;}catch(e){try{await c.query('ROLLBACK');}catch(_){}throw e;}finally{c.release();}}
async function changeStock(c,input){const productId=n(input.productId,'productId'),branchId=n(input.branchId,'branchId'),delta=n(input.quantityChange,'quantityChange',true);if(!delta)throw new Error('quantityChange cannot be zero');if(!TYPES.has(input.movementType))throw new Error('Unsupported movement type');await c.query('SELECT pg_advisory_xact_lock($1,$2)',[productId,branchId]);const p=await c.query('SELECT id FROM inventory_products_v3 WHERE id=$1 AND active=TRUE',[productId]);if(!p.rowCount)throw new Error('Active product not found');const b=await c.query('SELECT id FROM branches WHERE id=$1 AND is_active=TRUE',[branchId]);if(!b.rowCount)throw new Error('Active branch not found');await c.query('INSERT INTO inventory_stock_v3(product_id,branch_id,quantity_on_hand) VALUES($1,$2,0) ON CONFLICT(product_id,branch_id) DO NOTHING',[productId,branchId]);const locked=await c.query('SELECT quantity_on_hand FROM inventory_stock_v3 WHERE product_id=$1 AND branch_id=$2 FOR UPDATE',[productId,branchId]);const before=n(locked.rows[0].quantity_on_hand,'quantity_on_hand'),after=before+delta;if(after<0)throw new Error(`Insufficient stock: ${before} available`);await c.query('UPDATE inventory_stock_v3 SET quantity_on_hand=$3,updated_at=now() WHERE product_id=$1 AND branch_id=$2',[productId,branchId,after]);const m=await c.query(`INSERT INTO inventory_movements_v3(product_id,branch_id,movement_type,quantity_before,quantity_change,quantity_after,reference_type,reference_id,reason,user_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,[productId,branchId,input.movementType,before,delta,after,input.referenceType||null,input.referenceId==null?null:String(input.referenceId),input.reason||null,input.userId==null?null:n(input.userId,'userId')]);return {productId,branchId,quantityBefore:before,quantityAfter:after,movementId:m.rows[0].id};}
function mountInventoryV3(app){if(app.__inventoryV3Mounted)return;app.__inventoryV3Mounted=true;
app.get('/api/v3/inventory/products',async(req,res)=>{try{const branchId=n(req.query.branchId||1,'branchId'),q=s(req.query.q),params=[branchId];let where='p.active=TRUE';if(q){params.push(`%${q}%`);where+=` AND (p.name ILIKE $2 OR p.sku ILIKE $2 OR COALESCE(p.barcode,'') ILIKE $2)`;}const r=await db().query(`SELECT p.*,COALESCE(st.quantity_on_hand,0) quantity_on_hand FROM inventory_products_v3 p LEFT JOIN inventory_stock_v3 st ON st.product_id=p.id AND st.branch_id=$1 WHERE ${where} ORDER BY p.name`,params);res.set('Cache-Control','no-store').json({products:r.rows});}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/v3/inventory/dashboard',async(req,res)=>{try{const branchId=n(req.query.branchId||1,'branchId');const r=await db().query(`SELECT COUNT(*) FILTER(WHERE p.active)::bigint total_products,COUNT(*) FILTER(WHERE p.active AND COALESCE(st.quantity_on_hand,0)=0)::bigint out_of_stock_items,COUNT(*) FILTER(WHERE p.active AND COALESCE(st.quantity_on_hand,0)>0 AND COALESCE(st.quantity_on_hand,0)<=COALESCE(st.reorder_level,p.reorder_level))::bigint low_stock_items,COALESCE(SUM(CASE WHEN p.active THEN COALESCE(st.quantity_on_hand,0)*p.cost_price ELSE 0 END),0) inventory_cost_value,COALESCE(SUM(CASE WHEN p.active THEN COALESCE(st.quantity_on_hand,0) ELSE 0 END),0) total_units FROM inventory_products_v3 p LEFT JOIN inventory_stock_v3 st ON st.product_id=p.id AND st.branch_id=$1`,[branchId]);res.set('Cache-Control','no-store').json(r.rows[0]);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/v3/inventory/products',async(req,res)=>{try{const x=req.body||{},sku=s(x.sku),name=s(x.name);if(!sku||!name)throw new Error('SKU and product name are required');const product=await tx(async c=>{const r=await c.query(`INSERT INTO inventory_products_v3(sku,barcode,name,category,brand,unit,cost_price,selling_price,vat_rate,reorder_level,supplier_id,description) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[sku,s(x.barcode)||null,name,s(x.category)||null,s(x.brand)||null,s(x.unit)||'pcs',n(x.costPrice||0,'costPrice'),n(x.sellingPrice||0,'sellingPrice'),n(x.vatRate||0,'vatRate'),n(x.reorderLevel||0,'reorderLevel'),x.supplierId||null,s(x.description)||null]);if(x.branchId!=null){await changeStock(c,{productId:r.rows[0].id,branchId:x.branchId,quantityChange:n(x.openingStock||0,'openingStock'),movementType:'OPENING_BALANCE',referenceType:'PRODUCT_CREATE',referenceId:r.rows[0].id,reason:'Opening stock'}).catch(e=>{if(n(x.openingStock||0,'openingStock')===0)return;throw e;});}return r.rows[0];});res.status(201).json({product});}catch(e){res.status(e.code==='23505'?409:400).json({error:e.message});}});
app.post('/api/v3/inventory/receive',async(req,res)=>{try{const x=req.body||{};const r=await tx(c=>changeStock(c,{...x,quantityChange:n(x.quantity,'quantity'),movementType:'PURCHASE_RECEIPT'}));res.status(201).json(r);}catch(e){res.status(400).json({error:e.message});}});
app.post('/api/v3/inventory/adjust',async(req,res)=>{try{const x=req.body||{};const delta=n(x.quantityChange,'quantityChange',true);const r=await tx(c=>changeStock(c,{...x,quantityChange:delta,movementType:delta>0?'ADJUSTMENT_IN':'ADJUSTMENT_OUT'}));res.status(201).json(r);}catch(e){res.status(400).json({error:e.message});}});
app.get('/api/v3/inventory/movements',async(req,res)=>{try{const productId=n(req.query.productId,'productId'),branchId=n(req.query.branchId,'branchId');const r=await db().query('SELECT * FROM inventory_movements_v3 WHERE product_id=$1 AND branch_id=$2 ORDER BY created_at DESC,id DESC LIMIT 500',[productId,branchId]);res.json({movements:r.rows});}catch(e){res.status(400).json({error:e.message});}});
}
module.exports={mountInventoryV3,changeStock,TYPES};
