'use strict';
const {Pool}=require('pg');
const crypto=require('node:crypto');
const {parseAndValidateDatabaseUrl,railwaySsl}=require('../scripts/database-url.cjs');
let pool,ready;
function db(){if(!pool){const {databaseUrl}=parseAndValidateDatabaseUrl('quotations-v2');pool=new Pool({connectionString:databaseUrl,ssl:railwaySsl(databaseUrl),max:10});}return pool;}
const S=new Set(['DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED','CONVERTED']);
const n=(v,k='value')=>{const x=Number(v);if(!Number.isFinite(x)||x<0)throw Error(`Invalid ${k}`);return x};
const t=v=>String(v??'').trim();
async function ensureSchema(){if(ready)return ready;ready=(async()=>{await db().query(`
CREATE TABLE IF NOT EXISTS quotations_v2(
 id BIGSERIAL PRIMARY KEY, organisation_id BIGINT NOT NULL DEFAULT 1, branch_id BIGINT, number TEXT NOT NULL, customer_id BIGINT, customer_name TEXT, customer_email TEXT,
 status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED','CONVERTED')), issue_date DATE NOT NULL DEFAULT CURRENT_DATE, valid_until DATE,
 subtotal NUMERIC(14,2) NOT NULL DEFAULT 0, discount NUMERIC(14,2) NOT NULL DEFAULT 0, tax NUMERIC(14,2) NOT NULL DEFAULT 0, total NUMERIC(14,2) NOT NULL DEFAULT 0,
 notes TEXT, terms TEXT, created_by BIGINT, sent_at TIMESTAMPTZ, accepted_at TIMESTAMPTZ, converted_at TIMESTAMPTZ, converted_sale_id BIGINT,
 version INTEGER NOT NULL DEFAULT 1, parent_id BIGINT REFERENCES quotations_v2(id), share_token TEXT UNIQUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 UNIQUE(organisation_id,number,version));
CREATE TABLE IF NOT EXISTS quotation_items_v2(
 id BIGSERIAL PRIMARY KEY, quotation_id BIGINT NOT NULL REFERENCES quotations_v2(id) ON DELETE CASCADE, product_id BIGINT, description TEXT NOT NULL,
 qty NUMERIC(14,3) NOT NULL CHECK(qty>0), unit TEXT, unit_price NUMERIC(14,2) NOT NULL CHECK(unit_price>=0), discount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK(discount>=0), tax_rate NUMERIC(8,3) NOT NULL DEFAULT 0 CHECK(tax_rate>=0), line_total NUMERIC(14,2) NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS quotations_v2_org_date_idx ON quotations_v2(organisation_id,issue_date DESC);
CREATE INDEX IF NOT EXISTS quotations_v2_status_idx ON quotations_v2(organisation_id,status);
`);return true})().catch(e=>{ready=null;throw e});return ready;}
function totals(items){let subtotal=0,discount=0,tax=0;const rows=items.map((x,i)=>{const qty=n(x.qty,'qty'),price=n(x.unit_price??x.unitPrice,'unit price'),disc=n(x.discount??0,'discount'),rate=n(x.tax_rate??x.taxRate??0,'tax rate');if(disc>100)throw Error(`Line ${i+1} discount cannot exceed 100%`);const base=qty*price,discAmt=base*disc/100,taxAmt=(base-discAmt)*rate/100,total=base-discAmt+taxAmt;subtotal+=base;discount+=discAmt;tax+=taxAmt;return{product_id:x.product_id??x.productId??null,description:t(x.description)||`Custom line ${i+1}`,qty,unit:t(x.unit)||'pcs',unit_price:price,discount:disc,tax_rate:rate,line_total:total};});return{rows,subtotal,discount,tax,total:subtotal-discount+tax};}
async function nextNumber(c,org,issue){const year=new Date(issue||Date.now()).getFullYear();const prefix=`QT-${year}-`;const r=await c.query(`SELECT number FROM quotations_v2 WHERE organisation_id=$1 AND number LIKE $2 ORDER BY id DESC LIMIT 1`,[org,prefix+'%']);let seq=1;if(r.rowCount){const m=/-(\d+)$/.exec(r.rows[0].number);seq=(m?Number(m[1]):0)+1;}return prefix+String(seq).padStart(4,'0');}
function org(req){return Number(req.headers['x-organisation-id']||req.query.organisationId||req.body?.organisationId||1)||1;}
function actor(req){const x=req.headers['x-user-id']||req.body?.createdBy||null;return x==null?null:Number(x)||null;}
function role(req){return String(req.headers['x-role']||req.body?.role||'sales').toLowerCase();}
function allowedDiscount(req,items){const limit=n(req.body?.discountApprovalLimit??10,'discount approval limit');const max=Math.max(0,...items.map(x=>Number(x.discount)||0));if(max>limit&&!['manager','admin','owner'].includes(role(req)))throw Error(`Discount above ${limit}% requires manager approval`);}
function expire(){return db().query(`UPDATE quotations_v2 SET status='EXPIRED',updated_at=now() WHERE status IN ('DRAFT','SENT') AND valid_until IS NOT NULL AND valid_until<CURRENT_DATE`);}
async function load(id,organisationId){const q=await db().query('SELECT * FROM quotations_v2 WHERE id=$1 AND organisation_id=$2',[id,organisationId]);if(!q.rowCount)return null;const items=await db().query('SELECT * FROM quotation_items_v2 WHERE quotation_id=$1 ORDER BY id',[id]);return{...q.rows[0],items:items.rows};}
function mountQuotationsV2(app){if(app.__quotationsV2)return;app.__quotationsV2=true;const wrap=f=>async(req,res)=>{try{await ensureSchema();await expire();await f(req,res);}catch(e){res.status(e.message.includes('not found')?404:e.message.includes('requires manager')?403:400).json({error:e.message});}};
app.get('/api/quotations',wrap(async(req,res)=>{const o=org(req),a=[o];let where='organisation_id=$1';if(req.query.status&&S.has(String(req.query.status).toUpperCase())){a.push(String(req.query.status).toUpperCase());where+=` AND status=$${a.length}`;}if(req.query.from){a.push(req.query.from);where+=` AND issue_date>=$${a.length}`;}if(req.query.to){a.push(req.query.to);where+=` AND issue_date<=$${a.length}`;}if(req.query.q){a.push('%'+t(req.query.q)+'%');where+=` AND (number ILIKE $${a.length} OR COALESCE(customer_name,'') ILIKE $${a.length})`;}
const rows=await db().query(`SELECT * FROM quotations_v2 WHERE ${where} ORDER BY issue_date DESC,id DESC LIMIT 500`,a);const sum=await db().query(`SELECT COUNT(*)::int count,COALESCE(SUM(total),0) total FROM quotations_v2 WHERE ${where}`,a);res.set('Cache-Control','no-store').json({quotations:rows.rows,summary:sum.rows[0]});}));
app.get('/api/quotations/:id',wrap(async(req,res)=>{const x=await load(n(req.params.id,'id'),org(req));if(!x)return res.status(404).json({error:'Quotation not found'});res.json({quotation:x});}));
app.post('/api/quotations',wrap(async(req,res)=>{const x=req.body||{},o=org(req),items=Array.isArray(x.items)?x.items:[];if(!items.length)throw Error('At least one line item is required');allowedDiscount(req,items);const z=totals(items);const c=await db().connect();try{await c.query('BEGIN');const number=t(x.number)||await nextNumber(c,o,x.issueDate);const token=crypto.randomBytes(18).toString('base64url');const q=await c.query(`INSERT INTO quotations_v2(organisation_id,branch_id,number,customer_id,customer_name,customer_email,status,issue_date,valid_until,subtotal,discount,tax,total,notes,terms,created_by,share_token) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING *`,[o,x.branchId||null,number,x.customerId||null,t(x.customerName)||null,t(x.customerEmail)||null,S.has(String(x.status||'DRAFT').toUpperCase())?String(x.status||'DRAFT').toUpperCase():'DRAFT',x.issueDate||new Date().toISOString().slice(0,10),x.validUntil||null,z.subtotal,z.discount,z.tax,z.total,t(x.notes)||null,t(x.terms)||null,actor(req),token]);for(const r of z.rows)await c.query('INSERT INTO quotation_items_v2(quotation_id,product_id,description,qty,unit,unit_price,discount,tax_rate,line_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[q.rows[0].id,r.product_id,r.description,r.qty,r.unit,r.unit_price,r.discount,r.tax_rate,r.line_total]);await c.query('COMMIT');res.status(201).json({quotation:await load(q.rows[0].id,o)});}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();}}));
app.put('/api/quotations/:id',wrap(async(req,res)=>{const id=n(req.params.id,'id'),o=org(req),old=await load(id,o);if(!old)throw Error('Quotation not found');if(['CONVERTED'].includes(old.status))throw Error('Converted quotations cannot be edited; duplicate instead');const x=req.body||{},items=Array.isArray(x.items)?x.items:old.items;allowedDiscount(req,items);const z=totals(items);await db().query(`UPDATE quotations_v2 SET customer_id=$3,customer_name=$4,customer_email=$5,valid_until=$6,subtotal=$7,discount=$8,tax=$9,total=$10,notes=$11,terms=$12,status=$13,updated_at=now() WHERE id=$1 AND organisation_id=$2`,[id,o,x.customerId??old.customer_id,t(x.customerName??old.customer_name)||null,t(x.customerEmail??old.customer_email)||null,x.validUntil??old.valid_until,z.subtotal,z.discount,z.tax,z.total,t(x.notes??old.notes)||null,t(x.terms??old.terms)||null,S.has(String(x.status||old.status).toUpperCase())?String(x.status||old.status).toUpperCase():old.status]);await db().query('DELETE FROM quotation_items_v2 WHERE quotation_id=$1',[id]);for(const r of z.rows)await db().query('INSERT INTO quotation_items_v2(quotation_id,product_id,description,qty,unit,unit_price,discount,tax_rate,line_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[id,r.product_id,r.description,r.qty,r.unit,r.unit_price,r.discount,r.tax_rate,r.line_total]);res.json({quotation:await load(id,o)});}));
app.post('/api/quotations/:id/send',wrap(async(req,res)=>{const id=n(req.params.id,'id'),o=org(req),x=await load(id,o);if(!x)throw Error('Quotation not found');if(!x.customer_email)throw Error('Customer email is required before sending');await db().query(`UPDATE quotations_v2 SET status='SENT',sent_at=now(),updated_at=now() WHERE id=$1 AND organisation_id=$2`,[id,o]);res.json({quotation:await load(id,o),emailQueued:true});}));
app.post('/api/quotations/:id/status',wrap(async(req,res)=>{const status=String(req.body?.status||'').toUpperCase();if(!S.has(status)||status==='CONVERTED')throw Error('Invalid quotation status');const id=n(req.params.id,'id'),o=org(req);const r=await db().query(`UPDATE quotations_v2 SET status=$3,accepted_at=CASE WHEN $3='ACCEPTED' THEN now() ELSE accepted_at END,updated_at=now() WHERE id=$1 AND organisation_id=$2 RETURNING id`,[id,o,status]);if(!r.rowCount)throw Error('Quotation not found');res.json({quotation:await load(id,o)});}));
app.post('/api/quotations/:id/duplicate',wrap(async(req,res)=>{const id=n(req.params.id,'id'),o=org(req),x=await load(id,o);if(!x)throw Error('Quotation not found');const c=await db().connect();try{await c.query('BEGIN');const number=await nextNumber(c,o,new Date());const q=await c.query(`INSERT INTO quotations_v2(organisation_id,branch_id,number,customer_id,customer_name,customer_email,status,issue_date,valid_until,subtotal,discount,tax,total,notes,terms,created_by,version,parent_id,share_token) SELECT organisation_id,branch_id,$3,customer_id,customer_name,customer_email,'DRAFT',CURRENT_DATE,valid_until,subtotal,discount,tax,total,notes,terms,$4,version+1,id,$5 FROM quotations_v2 WHERE id=$1 AND organisation_id=$2 RETURNING id`,[id,o,number,actor(req),crypto.randomBytes(18).toString('base64url')]);for(const r of x.items)await c.query('INSERT INTO quotation_items_v2(quotation_id,product_id,description,qty,unit,unit_price,discount,tax_rate,line_total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[q.rows[0].id,r.product_id,r.description,r.qty,r.unit,r.unit_price,r.discount,r.tax_rate,r.line_total]);await c.query('COMMIT');res.status(201).json({quotation:await load(q.rows[0].id,o)});}catch(e){await c.query('ROLLBACK');throw e}finally{c.release();}}));
app.post('/api/quotations/:id/convert',wrap(async(req,res)=>{const id=n(req.params.id,'id'),o=org(req),x=await load(id,o);if(!x)throw Error('Quotation not found');if(x.status!=='ACCEPTED')throw Error('Only accepted quotations can be converted');const sale={source:'quotation',quotationId:x.id,customerId:x.customer_id,customerName:x.customer_name,items:x.items.map(r=>({productId:r.product_id,description:r.description,qty:Number(r.qty),unit:r.unit,unitPrice:Number(r.unit_price),discount:Number(r.discount),taxRate:Number(r.tax_rate),lineTotal:Number(r.line_total)})),subtotal:Number(x.subtotal),discount:Number(x.discount),tax:Number(x.tax),total:Number(x.total)};await db().query(`UPDATE quotations_v2 SET status='CONVERTED',converted_at=now(),updated_at=now() WHERE id=$1 AND organisation_id=$2`,[id,o]);res.json({sale,quotation:await load(id,o)});}));
app.delete('/api/quotations/:id',wrap(async(req,res)=>{if(!['manager','admin','owner'].includes(role(req)))return res.status(403).json({error:'Only a manager may delete quotations'});const r=await db().query('DELETE FROM quotations_v2 WHERE id=$1 AND organisation_id=$2 RETURNING id',[n(req.params.id,'id'),org(req)]);if(!r.rowCount)return res.status(404).json({error:'Quotation not found'});res.status(204).end();}));
app.get('/api/quotations/share/:token',wrap(async(req,res)=>{const r=await db().query('SELECT id,number,customer_name,status,issue_date,valid_until,subtotal,discount,tax,total,notes,terms FROM quotations_v2 WHERE share_token=$1',[t(req.params.token)]);if(!r.rowCount)return res.status(404).json({error:'Quotation not found'});const items=await db().query('SELECT description,qty,unit,unit_price,discount,tax_rate,line_total FROM quotation_items_v2 WHERE quotation_id=$1 ORDER BY id',[r.rows[0].id]);res.json({quotation:{...r.rows[0],items:items.rows}});}));}
module.exports={mountQuotationsV2,ensureSchema};