// Runtime route source injected by scripts/build.cjs.
const mpesaService = require('./server/services/mpesa/index.cjs');
const { sql: mpesaSql } = require('drizzle-orm');
function mpesaUserAllowed(req) { const role=String(req.user?.role||'').toLowerCase(); return ['cashier','sales_rep','branch_manager','accountant','business_owner','super_admin'].includes(role); }
function mpesaRows(result) { return result?.rows || result || []; }
function mpesaCallbackMessage(code, desc) { const map={1032:'The customer cancelled the M-Pesa payment.',2001:'The customer entered an incorrect M-Pesa PIN.',1:'The customer’s M-Pesa account has insufficient funds.',1037:'The M-Pesa request timed out or the customer’s phone could not be reached.'}; return map[Number(code)] || String(desc||'M-Pesa payment failed.').slice(0,240); }
function mpesaConfigSafe() { return mpesaService.mpesaConfig(process.env); }
async function resolveMpesaCallback(checkoutRequestId,resultCode,resultDesc,callbackBody) {
  return db.transaction(async(tx)=>{
    const found=mpesaRows(await tx.execute(mpesaSql`SELECT * FROM mpesa_transactions WHERE checkout_request_id=${checkoutRequestId} FOR UPDATE`))[0];
    if(!found) return {stored:false,status:'unknown'};
    if(['success','failed','cancelled','timeout'].includes(found.status)) return {stored:true,status:found.status};
    const metadata=callbackBody?.Body?.stkCallback?.CallbackMetadata?.Item||[];
    const item=name=>metadata.find(x=>x?.Name===name)?.Value;
    const code=Number(resultCode);
    if(code!==0){const status=code===1032?'cancelled':code===1037?'timeout':'failed';await tx.execute(mpesaSql`UPDATE mpesa_transactions SET status=${status},result_code=${code},result_desc=${String(resultDesc||'').slice(0,500)},raw_callback=${JSON.stringify(callbackBody)}::jsonb,updated_at=now() WHERE id=${found.id}`);return {stored:true,status};}
    const receipt=item('MpesaReceiptNumber'); const txDateRaw=item('TransactionDate');
    if(!receipt) throw new Error('Successful M-Pesa callback did not contain a receipt number.');
    const invoice=mpesaRows(await tx.execute(mpesaSql`SELECT id,total,amount_paid,balance_due,status,invoice_number FROM invoices WHERE id=${found.invoice_id} FOR UPDATE`))[0];
    if(!invoice) throw new Error('Invoice for M-Pesa transaction no longer exists.');
    const balance=Math.max(0,Number(invoice.balance_due||0));
    const paid=Math.min(Number(found.amount_kes),balance);
    const duplicate=mpesaRows(await tx.execute(mpesaSql`SELECT id FROM invoice_payments WHERE reference=${String(receipt).slice(0,255)} LIMIT 1`))[0];
    if(!duplicate && paid>0) await tx.execute(mpesaSql`INSERT INTO invoice_payments (invoice_id,amount,method,reference,notes,created_at) VALUES (${found.invoice_id},${paid},'mpesa',${String(receipt).slice(0,255)},${'Daraja STK Push checkout '+checkoutRequestId},now())`);
    const newPaid=Number(invoice.amount_paid||0)+(duplicate?0:paid); const newBalance=Math.max(0,Number(invoice.total||0)-newPaid); const newStatus=newBalance<=0?'paid':'partial';
    await tx.execute(mpesaSql`UPDATE invoices SET amount_paid=${newPaid},balance_due=${newBalance},status=${newStatus} WHERE id=${found.invoice_id}`);
    await tx.execute(mpesaSql`UPDATE mpesa_transactions SET status='success',result_code=0,result_desc=${String(resultDesc||'Success').slice(0,500)},mpesa_receipt_number=${String(receipt).slice(0,64)},transaction_date=${txDateRaw?String(txDateRaw):null},raw_callback=${JSON.stringify(callbackBody)}::jsonb,updated_at=now() WHERE id=${found.id}`);
    return {stored:true,status:'success',receipt,amount:paid};
  });
}

__MPESA_ROUTER__.post("/invoices/:id/mpesa/stk-push",requireAuth,async(req,res)=>{
  if(!mpesaUserAllowed(req)) return res.status(403).json({error:'You are not authorised to request M-Pesa payments.'});
  try{const id=Number(req.params.id);const invoice=mpesaRows(await db.execute(mpesaSql`SELECT id,invoice_number,total,amount_paid,balance_due,status,branch_id FROM invoices WHERE id=${id} LIMIT 1`))[0];if(!invoice||!isBranchInScope(req,invoice.branch_id))return res.status(404).json({error:'Invoice not found.'});const balance=Math.max(0,Number(invoice.total||0)-Number(invoice.amount_paid||0));if(!['draft','sent','partial','overdue'].includes(String(invoice.status))||balance<=0)return res.status(409).json({error:'This invoice has no payable balance.'});const config=mpesaConfigSafe();const phone=mpesaService.normalizeMpesaPhone(req.body?.phone);const pending=mpesaRows(await db.execute(mpesaSql`SELECT checkout_request_id FROM mpesa_transactions WHERE invoice_id=${id} AND status='pending' AND created_at>now()-interval '60 seconds' ORDER BY created_at DESC LIMIT 1`))[0];if(pending)return res.status(409).json({error:'A payment prompt is already pending for this invoice. Please wait before sending another.',checkoutRequestId:pending.checkout_request_id,status:'pending'});const result=await mpesaService.initiateStkPush(config,{phone,amountKes:Math.trunc(balance),invoiceNumber:invoice.invoice_number});await db.execute(mpesaSql`INSERT INTO mpesa_transactions(invoice_id,phone,amount_kes,merchant_request_id,checkout_request_id,status) VALUES(${id},${phone},${Math.trunc(balance)},${result.MerchantRequestID||null},${result.CheckoutRequestID},'pending')`);logger.info({event:'mpesa_stk_push_initiated',invoiceId:id,checkoutRequestId:result.CheckoutRequestID,amount:Math.trunc(balance),environment:config.env,userId:req.user?.id},'M-Pesa STK Push initiated');return res.json({checkoutRequestId:result.CheckoutRequestID,status:'pending',maskedPhone:mpesaService.maskMpesaPhone(phone)});}catch(error){logger.error({err:error,event:'mpesa_stk_push_failed'},'M-Pesa STK Push failed');return res.status(400).json({error:error.message||'Unable to initiate M-Pesa payment.'});}
});

__MPESA_ROUTER__.post("/public/mpesa/callback",async(req,res)=>{try{const callback=req.body?.Body?.stkCallback;if(!callback||typeof callback.CheckoutRequestID!=='string'||!Number.isInteger(Number(callback.ResultCode))||typeof callback.ResultDesc!=='string')throw new Error('Invalid M-Pesa callback payload.');logger.info({event:'mpesa_callback_received',checkoutRequestId:callback.CheckoutRequestID,resultCode:Number(callback.ResultCode)},'M-Pesa callback received');const resolved=await resolveMpesaCallback(callback.CheckoutRequestID,Number(callback.ResultCode),callback.ResultDesc,req.body);logger.info({event:'mpesa_callback_resolved',checkoutRequestId:callback.CheckoutRequestID,resultCode:Number(callback.ResultCode),status:resolved.status},'M-Pesa callback resolved');}catch(error){logger.error({err:error,event:'mpesa_callback_processing_error'},'M-Pesa callback processing error');}return res.status(200).json({ResultCode:0,ResultDesc:'Accepted'});});

__MPESA_ROUTER__.get("/invoices/:id/mpesa/status",requireAuth,async(req,res)=>{if(!mpesaUserAllowed(req))return res.status(403).json({error:'You are not authorised to view M-Pesa payment status.'});const id=Number(req.params.id),checkout=String(req.query.checkoutRequestId||'');if(!checkout)return res.status(400).json({error:'checkoutRequestId is required.'});const invoice=mpesaRows(await db.execute(mpesaSql`SELECT branch_id FROM invoices WHERE id=${id} LIMIT 1`))[0];if(!invoice||!isBranchInScope(req,invoice.branch_id))return res.status(404).json({error:'Invoice not found.'});const tx=mpesaRows(await db.execute(mpesaSql`SELECT checkout_request_id,status,amount_kes,result_code,result_desc,mpesa_receipt_number FROM mpesa_transactions WHERE invoice_id=${id} AND checkout_request_id=${checkout} LIMIT 1`))[0];if(!tx)return res.status(404).json({error:'M-Pesa transaction not found.'});const out={checkoutRequestId:tx.checkout_request_id,status:tx.status};if(tx.status==='success'){out.amount=Number(tx.amount_kes);out.mpesaReceiptNumber=tx.mpesa_receipt_number;}else if(tx.status!=='pending'){out.resultCode=tx.result_code;out.message=mpesaCallbackMessage(tx.result_code,tx.result_desc);}return res.json(out);});

__MPESA_ROUTER__.post("/invoices/:id/mpesa/query",requireAuth,async(req,res)=>{if(!mpesaUserAllowed(req))return res.status(403).json({error:'You are not authorised to query M-Pesa payments.'});try{const id=Number(req.params.id),checkout=String(req.body?.checkoutRequestId||'');const rows=mpesaRows(await db.execute(mpesaSql`SELECT checkout_request_id FROM mpesa_transactions WHERE invoice_id=${id} AND checkout_request_id=${checkout} AND status='pending' LIMIT 1`));if(!rows[0])return res.status(404).json({error:'Pending M-Pesa transaction not found.'});const result=await mpesaService.queryStkPush(mpesaConfigSafe(),{checkoutRequestId:checkout});return res.json({checkoutRequestId:checkout,responseCode:result.ResponseCode??null,responseDescription:result.ResponseDescription??null,resultCode:result.ResultCode??null,resultDesc:result.ResultDesc??null});}catch(error){return res.status(400).json({error:error.message||'M-Pesa query failed.'});}});
