'use strict';

const fs = require('node:fs');
const path = require('node:path');
const zlib = require('node:zlib');
const { spawnSync } = require('node:child_process');

const root = path.resolve(__dirname, '..');
const pdfDir = path.join(root, 'server', 'pdf');
const fontRegular = require.resolve('@fontsource/dejavu-sans/files/latin-400-normal.ttf');
let fontBold;
try { fontBold = require.resolve('@fontsource/dejavu-sans/files/latin-700-normal.ttf'); } catch { fontBold = require.resolve('@fontsource/dejavu-sans/files/latin-400-normal.ttf'); }
function packed(file) { return zlib.gzipSync(fs.readFileSync(file), { level: 9 }).toString('base64'); }
fs.mkdirSync(pdfDir, { recursive: true });
const generated = `'use strict';\n// Generated by scripts/build.cjs. Do not edit manually.\nconst zlib = require('node:zlib');\nconst inflate = (s) => zlib.gunzipSync(Buffer.from(s, 'base64')).toString('base64');\nmodule.exports = { regular: inflate(${JSON.stringify(packed(fontRegular))}), bold: inflate(${JSON.stringify(packed(fontBold))}) };\n`;
fs.writeFileSync(path.join(pdfDir, 'fonts.generated.cjs'), generated);

const requiredFiles = [
  'app.js', 'index.cjs', 'product-bulk.cjs', 'public/index.html', 'public/app.js', 'public/styles.css', 'public/quotation-custom-items.js',
  'server/pdf/index.cjs', 'server/pdf/schema.cjs', 'server/pdf/format.js', 'server/pdf/fonts.js', 'server/pdf/legacy.cjs', 'server/pdf/bundle-loader.cjs',
  'scripts/bootstrap-db.cjs', 'scripts/database-url.cjs', 'scripts/run-migrations.cjs', 'scripts/schema-config.cjs', 'scripts/sql-utils.cjs', 'scripts/validate-startup-env.cjs'
];
for (const file of requiredFiles) if (!fs.existsSync(path.join(root, file))) throw new Error(`Missing required runtime file: ${file}`);
for (const file of requiredFiles.filter((file) => file.endsWith('.js') || file.endsWith('.cjs'))) {
  const result = spawnSync(process.execPath, ['--check', path.join(root, file)], { stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status || 1);
}
console.log('[build] Embedded DejaVu Sans regular/bold font bundle generated.');
